export const dinoCatalog = [
    'Velociraptor',
    'Tyrannosaurus',
    'Triceratops',
    'Spinosaurus',
    'Allosaurus',
    'Brachiosaurus',
    'Stegosaurus',
    'Ankylosaurus',
    'Carnotaurus',
    'Giganotosaurus',
    'Baryonyx',
    'Iguanodon',
    'Dilophosaurus',
    'Pachycephalosaurus',
    'Parasaurolophus',
    'Therizinosaurus',

    'Apatosaurus',
    'Diplodocus',
    'Compsognathus',
    'Deinonychus',
    'Utahraptor',
    'Microraptor',
    'Oviraptor',
    'Troodon',
    'Albertosaurus',
    'Carcharodontosaurus',
    'Mapusaurus',
    'Suchomimus',
    'Acrocanthosaurus',
    'Megalosaurus',

    'Maiasaura',
    'Corythosaurus',
    'Lambeosaurus',
    'Edmontosaurus',
    'Hadrosaurus',
    'Saurolophus',
    'Tsintaosaurus',

    'Styracosaurus',
    'Centrosaurus',
    'Pentaceratops',
    'Chasmosaurus',
    'Protoceratops',
    'Psittacosaurus',

    'Euoplocephalus',
    'Nodosaurus',
    'Sauropelta',

    'Archaeopteryx',
    'Yi',
    'Confuciusornis',

    'Plateosaurus',
    'Massospondylus',
    'Riojasaurus',

    'Amargasaurus',
    'Argentinosaurus',
    'Patagotitan',
    'Dreadnoughtus',
    'Saltasaurus',
    'Mamenchisaurus',

    'Kentrosaurus',
    'Huayangosaurus',

    'Herrerasaurus',
    'Eoraptor',
    'Coelophysis',

    'Pteranodon',
    'Quetzalcoatlus',
    'Dimorphodon',

    'Ichthyosaurus',
    'Plesiosaurus',
    'Mosasaurus'
];
